In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from mpl_toolkits.mplot3d import Axes3D

def f(x,y):
    return (x**2+y-11)**2 + (x+y**2-7)**2

def gradf (x,y):
    return np.array([(2*(-7 + x + y**2 + 2*x*(-11 + x**2 + y))), (2*(-11 + x**2 + y + 2*y*(-7 + x + y**2)) )])

def dx(x,y):
    return 2*(-7 + x + y**2 + 2*x*(-11 + x**2 + y))

def dy(x,y):
    return 2*(-11 + x**2 + y + 2*y*(-7 + x + y**2))  

dx: 2 (-7 + x + y^2 + 2 x (-11 + x^2 + y))

dy: 2 (-11 + x^2 + y + 2 y (-7 + x + y^2))

# ADAM

In [2]:
def adam(f, gradf, x0, y0, lr=0.01, lrf=10, k=0.1, km=0.9, kms=0.9, N=100):
    """Adam GD

    Args:
        f (_type_): function
        gradf (_type_): gradient of a fucntion
        x0 (_type_): start pos x
        y0 (_type_): start pos y
        lr (float, optional): learning rate. Defaults to 0.01.
        lrf (int, optional): learning rate fall off. Defaults to 10.
        k (float, optional): factor of decreasing learning rate . Defaults to 0.1.
        km (float, optional): factor of momentum. Defaults to 0.9.
        kms (float, optional): factor of momentum smoothing. Defaults to 0.9.
        N (int): Iterations count. Defaults to 100.
    """
    m = np.zeros(gradf(x0 ,y0).shape)
    gradSq = np.zeros((gradf(x0,y0)**2).shape)

    for i in range(N):
        if (i%lrf) == 0:
            lr*=k
        m=km*m-lr*(1-km)*gradf(x0,y0)
        gradSq=kms*gradSq+(1-kms)*gradf(x0,y0)**2

        n = (lr*gradf(x0,y0)*m)/(gradSq+10**(-6))**0.5

        x = x0-n[0]
        y = y0-n[1]
    return x,y, f(x,y)


In [3]:
#набор точек
z, y = datasets.make_blobs(n_samples=10, centers=2, n_features=2, random_state=0)
y = np.zeros(10)
x = np.zeros(10)
# Нам нужно сравнить размерности массивов
#y=np.reshape(y,x.shape)
for i in range(len(z)):
    x[i],y[i] = z[i];
x, y

(array([ 1.12031365, -0.49772229,  1.9263585 ,  2.49913075,  3.54934659,
         1.7373078 ,  2.91970372,  2.84382807,  0.87305123,  2.36833522]),
 array([5.75806083, 1.55128226, 4.15243012, 1.23133799, 0.6925054 ,
        4.42546234, 0.15549864, 3.32650945, 4.71438583, 0.04356792]))

In [4]:
adam(f,gradf,x,y,lr=0.1,lrf=50,km=0.8,kms=0.9)

(array([ 1.12035034, -0.49771416,  1.92635866,  2.49917195,  3.54937317,
         1.73731173,  2.91973893,  2.8438466 ,  0.87306414,  2.36839515]),
 array([5.75868117, 1.55133226, 4.152626  , 1.23135974, 0.69250905,
        4.42570879, 0.1555058 , 3.32660223, 4.7146784 , 0.04357942]),
 array([760.23820886, 110.57657063, 157.96273198,  21.31770305,
         14.07384632, 217.82840799,  21.83240824,  47.9213328 ,
        289.75488258,  50.02592043]))