In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from mpl_toolkits.mplot3d import Axes3D

def f(x,y):
    return (x**2+y-11)**2 + (x+y**2-7)**2

def gradf (x,y):
    return np.array([(2*(-7 + x + y**2 + 2*x*(-11 + x**2 + y))), (2*(-11 + x**2 + y + 2*y*(-7 + x + y**2)) )])

def dx(x,y):
    return 2*(-7 + x + y**2 + 2*x*(-11 + x**2 + y))

def dy(x,y):
    return 2*(-11 + x**2 + y + 2*y*(-7 + x + y**2))  

dx: 2 (-7 + x + y^2 + 2 x (-11 + x^2 + y))

dy: 2 (-11 + x^2 + y + 2 y (-7 + x + y^2))

# Moment

In [6]:
def moment(f, gradf, x0, y0, lr=0.01, lrf=10, k=0.1, km=0.9, kms=0.9, N=300):
    """moment GD

    Args:
        f (_type_): function
        gradf (_type_): gradient of a fucntion
        x0 (_type_): start pos x
        y0 (_type_): start pos y
        lr (float, optional): learning rate. Defaults to 0.01.
        lrf (int, optional): learning rate fall off. Defaults to 10.
        k (float, optional): factor of decreasing learning rate . Defaults to 0.1.
        km (float, optional): factor of momentum. Defaults to 0.9.
        N (int): Iterations count. Defaults to 300.
    """
    x_old = x0;
    y_old = y0;
    n = np.zeros(gradf(x0,y0).shape)
    for i in range(N):
        if ((i%lrf)==0):
            lr *= k
        n = km*n - lr*gradf(x0+km*n[0], y0+km*n[1])
        x = x_old - lr*n[0]
        y = y_old - lr*n[1]
        
    return x, y, f(x, y)


In [3]:
#набор точек
z, y = datasets.make_blobs(n_samples=10, centers=2, n_features=2, random_state=0)
y = np.zeros(10)
x = np.zeros(10)
# Нам нужно сравнить размерности массивов
#y=np.reshape(y,x.shape)
for i in range(len(z)):
    x[i],y[i] = z[i];
x, y

(array([ 1.12031365, -0.49772229,  1.9263585 ,  2.49913075,  3.54934659,
         1.7373078 ,  2.91970372,  2.84382807,  0.87305123,  2.36833522]),
 array([5.75806083, 1.55128226, 4.15243012, 1.23133799, 0.6925054 ,
        4.42546234, 0.15549864, 3.32650945, 4.71438583, 0.04356792]))

In [7]:
moment(f,gradf,x,y,lr=0.1,lrf=50,km=0.8,kms=0.9)

(array([ 1.12031365, -0.49772229,  1.9263585 ,  2.49913075,  3.54934659,
         1.7373078 ,  2.91970372,  2.84382807,  0.87305123,  2.36833522]),
 array([5.75806083, 1.55128226, 4.15243012, 1.23133799, 0.6925054 ,
        4.42546234, 0.15549864, 3.32650945, 4.71438583, 0.04356792]),
 array([759.8520326 , 110.57900416, 157.92436535,  21.31987261,
         14.07315326, 217.76765763,  21.83369908,  47.91238225,
        289.66911884,  50.0296433 ]))